version: '3.3'
services:
  server:
    image: blinkoliver/rest-api-server
    container_name: rest-api-server
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    environment:
      - DB_TYPE=${DB_TYPE}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - PORT=${PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rest-network
    restart: unless-stopped
    command: npm start
  db:
    image: blinkoliver/rest-api-db
    restart: unless-stopped
    container_name: rest-api-db
    build: ./db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    command: postgres -c logging_collector=on
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - rest-network

networks:
  rest-network:
    driver: bridge
volumes:
  pgdata:
