version: '3.3'
services:
  api:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      - homelibrary
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c 'npm run typeorm:migration && npm run start:dev'
  db:
    build: ./database/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PG_DATA=${POSTGRES_DB_DATA_PATH}
    volumes:
      - db-data:${POSTGRES_DB_DATA_PATH}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    networks:
      - homelibrary

networks:
  homelibrary:
    driver: bridge
volumes:
  db-data:
