version: '3.3'
services:
  server:
    container_name: rest-api-server
    image: blivkoliver/rest-api-server
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - rest-network
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: unless-stopped
  postgres:
    container_name: rest-api-db
    image: blinkoliver/rest-api-db
    build: ./db/
    command: postgres -c logging_collector=on
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - rest-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    restart: unless-stopped

networks:
  rest-network:
    driver: bridge
volumes:
  pgdata:
