version: '3.3'
services:
  server:
    container_name: rest-service-server
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    environment:
      - PORT=${PORT}
      #
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    networks:
      - rest-network
    restart: unless-stopped
    command: npm start
  database:
    container_name: rest-service-database
    build: ./db/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # 
    command: postgres -c logging_collector=on
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - rest-network
    restart: always

networks:
  rest-network:
    driver: bridge
volumes:
  postgres:
