services:
  server:
    container_name: rest-service
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run start:dev
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - rest-network
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: always
  database:
    container_name: rest-service-database
    build:
      dockerfile: ./database/Dockerfile
      context: ./database/
    command: postgres -c logging_collector=on
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql/postgresql.log
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - rest-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
networks:
  rest-network:
    name: rest-network
    driver: bridge
volumes:
  postgres_logs:
  postgres_data: